test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use bin/rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# supabase:
#   service: S3
#   endpoint: 'https://dsrweebolpprswxqnznb.supabase.co/storage/v1/s3/'
#   access_key_id: <%= Rails.application.credentials.dig(:supabase, :access_key_id) %>
#   secret_access_key: <%= Rails.application.credentials.dig(:supabase, :secret_access_key) %>
#   bucket: images
#   region: eu-central-1
#   force_path_style: true

yandex:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:yandex, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:yandex, :secret_access_key) %>
  bucket: rails-images
  region: ru-central1
  endpoint: https://storage.yandexcloud.net
  force_path_style: true
#
# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Use bin/rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
